source: src
destination: _site

title: Fruit Warehouse
description: Give me a banana. I'll give you a monkey.

baseurl: "/FruitWarehouse/"
url: "http://jungllle.github.io"

markdown: kramdown

sass:
  style: :compressed
